import type { CpvEntry } from "./types";

/**
 * Comprehensive CPV library for Flotek's services. Codes are 8 digits (the
 * check digit that appears after a hyphen in notices is stripped). The
 * "group" links each code to a keyword group so the score can name the service.
 *
 * Matching rules (scoring.ts): exact code = strongest, same 5-digit class =
 * medium, same 4-digit category = weak, same 2-digit division = minimal.
 */
export const DEFAULT_CPV_LIBRARY: CpvEntry[] = [
  // ---- Telecoms & voice (64xxxxxx) ----
  { code: "64200000", label: "Telecommunications services", group: "telecoms" },
  { code: "64210000", label: "Telephone and data transmission services", group: "telecoms" },
  { code: "64211000", label: "Public-telephone services", group: "telecoms" },
  { code: "64211100", label: "Local-telephone services", group: "telecoms" },
  { code: "64211200", label: "Long-distance telephone services", group: "telecoms" },
  { code: "64212000", label: "Mobile-telephone services", group: "telecoms" },
  { code: "64213000", label: "Shared business telephone network services", group: "telecoms" },
  { code: "64214000", label: "Dedicated business telephone network services", group: "telecoms" },
  { code: "64214100", label: "Satellite circuit rental services", group: "connectivity" },
  { code: "64214200", label: "Telephone switchboard services", group: "telecoms" },
  { code: "64214400", label: "Land-line rental services", group: "telecoms" },
  { code: "64215000", label: "IP telephone services", group: "telecoms" },
  { code: "64216000", label: "Electronic message and information services", group: "telecoms" },
  { code: "64220000", label: "Telecommunication services except telephone and data transmission", group: "telecoms" },
  { code: "64221000", label: "Interconnection services", group: "connectivity" },
  { code: "64227000", label: "Integrated telecommunications services", group: "telecoms" },
  { code: "64228000", label: "Television and radio broadcast transmission services", group: "av" },
  // ---- Telephone / network equipment (32xxxxxx) ----
  { code: "32400000", label: "Networks", group: "networking" },
  { code: "32410000", label: "Local area network", group: "networking" },
  { code: "32411000", label: "Token-ring network", group: "networking" },
  { code: "32412000", label: "Communications network", group: "networking" },
  { code: "32412100", label: "Telecommunications network", group: "telecoms" },
  { code: "32412110", label: "Internet network", group: "connectivity" },
  { code: "32412120", label: "Intranet network", group: "networking" },
  { code: "32413000", label: "Integrated network", group: "networking" },
  { code: "32413100", label: "Network routers", group: "networking" },
  { code: "32415000", label: "Ethernet network", group: "networking" },
  { code: "32416000", label: "ISDN network", group: "telecoms" },
  { code: "32417000", label: "Multimedia networks", group: "networking" },
  { code: "32418000", label: "Radio network", group: "connectivity" },
  { code: "32420000", label: "Network equipment", group: "networking" },
  { code: "32421000", label: "Network cabling", group: "cabling" },
  { code: "32422000", label: "Network components", group: "networking" },
  { code: "32423000", label: "Network hubs", group: "networking" },
  { code: "32424000", label: "Network infrastructure", group: "networking" },
  { code: "32425000", label: "Network operating system", group: "networking" },
  { code: "32426000", label: "Network publishing system", group: "networking" },
  { code: "32427000", label: "Network system", group: "networking" },
  { code: "32428000", label: "Network upgrade", group: "networking" },
  { code: "32429000", label: "Telephone network equipment", group: "telecoms" },
  { code: "32430000", label: "Wide area network", group: "connectivity" },
  { code: "32440000", label: "Telemetry and terminal equipment", group: "networking" },
  { code: "32500000", label: "Telecommunications equipment and supplies", group: "telecoms" },
  { code: "32510000", label: "Wireless telecommunications system", group: "networking" },
  { code: "32520000", label: "Telecommunications cable and equipment", group: "cabling" },
  { code: "32521000", label: "Telecommunications cable", group: "cabling" },
  { code: "32522000", label: "Telecommunications equipment", group: "telecoms" },
  { code: "32523000", label: "Telecommunications facilities", group: "telecoms" },
  { code: "32524000", label: "Telecommunications system", group: "telecoms" },
  { code: "32540000", label: "Switchboards", group: "telecoms" },
  { code: "32541000", label: "Switchboard equipment", group: "telecoms" },
  { code: "32550000", label: "Telephone equipment", group: "telecoms" },
  { code: "32551000", label: "Telephone cables and associated equipment", group: "cabling" },
  { code: "32552000", label: "Electrical apparatus for line telephony or line telegraphy", group: "telecoms" },
  { code: "32552100", label: "Telephone sets", group: "telecoms" },
  { code: "32552300", label: "Telephonic or telegraphic switching apparatus", group: "telecoms" },
  { code: "32552400", label: "Audio-frequency signal conversion apparatus", group: "telecoms" },
  { code: "32562000", label: "Optical-fibre cables", group: "cabling" },
  { code: "32562100", label: "Optical-fibre cables for information transmission", group: "cabling" },
  { code: "32562200", label: "Optical telecommunication cables", group: "cabling" },
  { code: "32562300", label: "Optical-fibre cables for data transmission", group: "cabling" },
  { code: "32570000", label: "Communications equipment", group: "telecoms" },
  { code: "32571000", label: "Communications infrastructure", group: "cabling" },
  { code: "32572000", label: "Communications cable", group: "cabling" },
  { code: "32573000", label: "Communications control system", group: "telecoms" },
  { code: "32580000", label: "Data equipment", group: "networking" },
  { code: "32581000", label: "Data-communications equipment", group: "networking" },
  { code: "32581100", label: "Data-transmission cable", group: "cabling" },
  { code: "32581200", label: "Fax equipment", group: "telecoms" },
  // ---- CCTV & AV ----
  { code: "32230000", label: "Radio transmission apparatus with reception apparatus", group: "connectivity" },
  { code: "32232000", label: "Video-conferencing equipment", group: "av" },
  { code: "32320000", label: "Television and audio-visual equipment", group: "av" },
  { code: "32321000", label: "Television projection equipment", group: "av" },
  { code: "32321200", label: "Audio-visual equipment", group: "av" },
  { code: "32321300", label: "Audio-visual materials", group: "av" },
  { code: "32322000", label: "Multimedia equipment", group: "av" },
  { code: "32323000", label: "Video monitors", group: "av" },
  { code: "32323500", label: "Video-surveillance system", group: "cctv" },
  { code: "32324000", label: "Televisions", group: "av" },
  { code: "32330000", label: "Apparatus for sound, video recording and reproduction", group: "av" },
  { code: "32340000", label: "Microphones and loudspeakers", group: "av" },
  { code: "32342400", label: "Acoustic devices", group: "av" },
  { code: "32351200", label: "Screens", group: "av" },
  { code: "35120000", label: "Surveillance and security systems and devices", group: "cctv" },
  { code: "35121000", label: "Security equipment", group: "cctv" },
  { code: "35121700", label: "Alarm systems", group: "cctv" },
  { code: "35123000", label: "Installation identification equipment", group: "cctv" },
  { code: "35123300", label: "Time-attendance system", group: "cctv" },
  { code: "35123400", label: "Identification badges", group: "cctv" },
  { code: "35123500", label: "Video identification systems", group: "cctv" },
  { code: "35124000", label: "Metal detectors", group: "cctv" },
  { code: "35125000", label: "Surveillance system", group: "cctv" },
  { code: "35125100", label: "Sensors", group: "cctv" },
  { code: "35125300", label: "Security cameras", group: "cctv" },
  { code: "42961100", label: "Access control system", group: "cctv" },
  { code: "45312200", label: "Burglar-alarm system installation work", group: "cctv" },
  { code: "51310000", label: "Installation services of radio, television, sound and video equipment", group: "av" },
  { code: "51314000", label: "Video equipment installation services", group: "av" },
  { code: "79711000", label: "Alarm-monitoring services", group: "cctv" },
  { code: "79714000", label: "Surveillance services", group: "cctv" },
  { code: "92224000", label: "Digital television", group: "av" },
  // ---- Cabling & installation (45xxxxxx / 51xxxxxx) ----
  { code: "45310000", label: "Electrical installation work", group: "cabling" },
  { code: "45311000", label: "Electrical wiring and fitting work", group: "cabling" },
  { code: "45314000", label: "Installation of telecommunications equipment", group: "cabling" },
  { code: "45314100", label: "Installation of telephone exchanges", group: "telecoms" },
  { code: "45314120", label: "Installation of switchboards", group: "telecoms" },
  { code: "45314200", label: "Installation of telephone lines", group: "cabling" },
  { code: "45314300", label: "Installation of cable infrastructure", group: "cabling" },
  { code: "45314310", label: "Installation of cable laying", group: "cabling" },
  { code: "45314320", label: "Installation of computer cabling", group: "cabling" },
  { code: "45315000", label: "Electrical installation work of heating and other electrical building-equipment", group: "cabling" },
  { code: "45316000", label: "Installation work of illumination and signalling systems", group: "cabling" },
  { code: "45232300", label: "Construction and ancillary works for telephone and communication lines", group: "cabling" },
  { code: "45232310", label: "Construction work for telephone lines", group: "cabling" },
  { code: "45232320", label: "Cabled broadcasting lines", group: "cabling" },
  { code: "45232330", label: "Erection of aerials", group: "connectivity" },
  { code: "45232332", label: "Ancillary works for telecommunications", group: "cabling" },
  { code: "51300000", label: "Installation services of communications equipment", group: "cabling" },
  { code: "51320000", label: "Installation services of radio and television transmitters", group: "connectivity" },
  { code: "51340000", label: "Installation services of line telephony equipment", group: "telecoms" },
  { code: "51350000", label: "Installation services of line telegraphy equipment", group: "telecoms" },
  { code: "51600000", label: "Installation services of computers and office equipment", group: "managedit" },
  { code: "51610000", label: "Installation services of computers and information-processing equipment", group: "managedit" },
  { code: "51611000", label: "Installation services of computers", group: "managedit" },
  { code: "51611100", label: "Hardware installation services", group: "managedit" },
  { code: "51612000", label: "Installation services of information-processing equipment", group: "managedit" },
  { code: "50330000", label: "Maintenance services of telecommunications equipment", group: "telecoms" },
  { code: "50331000", label: "Repair and maintenance services of telecommunications lines", group: "telecoms" },
  { code: "50332000", label: "Telecommunications-infrastructure maintenance services", group: "telecoms" },
  { code: "50333000", label: "Maintenance services of radio-communications equipment", group: "telecoms" },
  { code: "50334000", label: "Repair and maintenance services of line telephony and line telegraphy equipment", group: "telecoms" },
  { code: "50334100", label: "Repair and maintenance services of line telephony equipment", group: "telecoms" },
  { code: "50334110", label: "Maintenance services of telephone network", group: "telecoms" },
  { code: "50334120", label: "Upgrading services of telephone switching equipment", group: "telecoms" },
  { code: "50334130", label: "Repair and maintenance services of telephone switching apparatus", group: "telecoms" },
  { code: "50334140", label: "Repair and maintenance services of telephone sets", group: "telecoms" },
  { code: "50300000", label: "Repair, maintenance and associated services related to personal computers and office equipment", group: "managedit" },
  { code: "50310000", label: "Maintenance and repair of office machinery", group: "managedit" },
  { code: "50312000", label: "Maintenance and repair of computer equipment", group: "managedit" },
  { code: "50312300", label: "Maintenance and repair of data network equipment", group: "networking" },
  { code: "50312310", label: "Maintenance of data network equipment", group: "networking" },
  { code: "50312320", label: "Repair of data network equipment", group: "networking" },
  { code: "50312600", label: "Maintenance and repair of information technology equipment", group: "managedit" },
  { code: "50312610", label: "Maintenance of information technology equipment", group: "managedit" },
  { code: "50312620", label: "Repair of information technology equipment", group: "managedit" },
  { code: "50320000", label: "Repair and maintenance services of personal computers", group: "managedit" },
  { code: "50324000", label: "Support services of personal computers", group: "managedit" },
  { code: "50324100", label: "System maintenance services", group: "managedit" },
  { code: "50324200", label: "Preventive maintenance services", group: "managedit" },
  { code: "50340000", label: "Repair and maintenance services of audio-visual and optical equipment", group: "av" },
  { code: "50343000", label: "Repair and maintenance services of video equipment", group: "av" },
  { code: "50610000", label: "Repair and maintenance services of security equipment", group: "cctv" },
  // ---- IT services (72xxxxxx) ----
  { code: "72000000", label: "IT services: consulting, software development, Internet and support", group: "managedit" },
  { code: "72100000", label: "Hardware consultancy services", group: "managedit" },
  { code: "72110000", label: "Hardware selection consultancy services", group: "managedit" },
  { code: "72120000", label: "Hardware disaster-recovery consultancy services", group: "cyber" },
  { code: "72130000", label: "Computer-site planning consultancy services", group: "managedit" },
  { code: "72140000", label: "Computer hardware acceptance testing consultancy services", group: "managedit" },
  { code: "72150000", label: "Computer audit consultancy and hardware consultancy services", group: "managedit" },
  { code: "72200000", label: "Software programming and consultancy services", group: "managedit" },
  { code: "72220000", label: "Systems and technical consultancy services", group: "managedit" },
  { code: "72221000", label: "Business analysis consultancy services", group: "managedit" },
  { code: "72222000", label: "Information systems or technology strategic review and planning services", group: "managedit" },
  { code: "72222100", label: "Information systems or technology strategic review services", group: "managedit" },
  { code: "72222200", label: "Information systems or technology planning services", group: "managedit" },
  { code: "72222300", label: "Information technology services", group: "managedit" },
  { code: "72223000", label: "Information technology requirements review services", group: "managedit" },
  { code: "72224000", label: "Project management consultancy services", group: "managedit" },
  { code: "72224100", label: "System implementation planning services", group: "managedit" },
  { code: "72224200", label: "System quality assurance planning services", group: "managedit" },
  { code: "72225000", label: "System quality assurance assessment and review services", group: "managedit" },
  { code: "72226000", label: "System software acceptance testing consultancy services", group: "managedit" },
  { code: "72227000", label: "Software integration consultancy services", group: "managedit" },
  { code: "72228000", label: "Hardware integration consultancy services", group: "managedit" },
  { code: "72212730", label: "Security software development services", group: "cyber" },
  { code: "72212731", label: "File security software development services", group: "cyber" },
  { code: "72212732", label: "Data security software development services", group: "cyber" },
  { code: "72212517", label: "IT software development services", group: "managedit" },
  { code: "72212900", label: "Miscellaneous software development services and computer systems", group: "managedit" },
  { code: "72212920", label: "Office automation software development services", group: "microsoft" },
  { code: "72212930", label: "Training and entertainment software development services", group: "managedit" },
  { code: "72212950", label: "Communication and multimedia software development services", group: "telecoms" },
  { code: "72212960", label: "Communication software development services", group: "telecoms" },
  { code: "72212970", label: "Multimedia software development services", group: "av" },
  { code: "72212980", label: "Communications software development services", group: "telecoms" },
  { code: "72212990", label: "Interactive software development services", group: "managedit" },
  { code: "72250000", label: "System and support services", group: "managedit" },
  { code: "72251000", label: "Disaster recovery services", group: "cyber" },
  { code: "72252000", label: "Computer archiving services", group: "cloud" },
  { code: "72253000", label: "Helpdesk and support services", group: "managedit" },
  { code: "72253100", label: "Helpdesk services", group: "managedit" },
  { code: "72253200", label: "Systems support services", group: "managedit" },
  { code: "72254000", label: "Software testing", group: "managedit" },
  { code: "72254100", label: "Systems testing services", group: "managedit" },
  { code: "72260000", label: "Software-related services", group: "managedit" },
  { code: "72261000", label: "Software support services", group: "managedit" },
  { code: "72263000", label: "Software implementation services", group: "managedit" },
  { code: "72265000", label: "Software configuration services", group: "managedit" },
  { code: "72266000", label: "Software consultancy services", group: "managedit" },
  { code: "72267000", label: "Software maintenance and repair services", group: "managedit" },
  { code: "72267100", label: "Maintenance of information technology software", group: "managedit" },
  { code: "72267200", label: "Repair of information technology software", group: "managedit" },
  { code: "72268000", label: "Software supply services", group: "microsoft" },
  { code: "72300000", label: "Data services", group: "cloud" },
  { code: "72310000", label: "Data-processing services", group: "cloud" },
  { code: "72315000", label: "Data network management and support services", group: "networking" },
  { code: "72315100", label: "Data network support services", group: "networking" },
  { code: "72315200", label: "Data network management services", group: "networking" },
  { code: "72317000", label: "Data storage services", group: "cloud" },
  { code: "72318000", label: "Data transmission services", group: "connectivity" },
  { code: "72400000", label: "Internet services", group: "connectivity" },
  { code: "72410000", label: "Provider services", group: "connectivity" },
  { code: "72411000", label: "Internet service providers ISP", group: "connectivity" },
  { code: "72412000", label: "Electronic mail service provider", group: "microsoft" },
  { code: "72413000", label: "World wide web (www) site design services", group: "managedit" },
  { code: "72414000", label: "Web search engine providers", group: "managedit" },
  { code: "72415000", label: "World wide web (www) site operation host services", group: "cloud" },
  { code: "72416000", label: "Application service providers", group: "cloud" },
  { code: "72417000", label: "Internet domain names", group: "managedit" },
  { code: "72420000", label: "Internet development services", group: "managedit" },
  { code: "72500000", label: "Computer-related services", group: "managedit" },
  { code: "72510000", label: "Computer-related management services", group: "managedit" },
  { code: "72511000", label: "Network management software services", group: "networking" },
  { code: "72512000", label: "Document management services", group: "microsoft" },
  { code: "72513000", label: "Office automation services", group: "microsoft" },
  { code: "72514000", label: "Computer facilities management services", group: "managedit" },
  { code: "72514100", label: "Facilities management services involving computer operation", group: "managedit" },
  { code: "72514200", label: "Facilities management services for computer systems development", group: "managedit" },
  { code: "72514300", label: "Facilities management services for computer systems maintenance", group: "managedit" },
  { code: "72540000", label: "Computer upgrade services", group: "managedit" },
  { code: "72541000", label: "Computer expansion services", group: "managedit" },
  { code: "72590000", label: "Computer-related professional services", group: "managedit" },
  { code: "72591000", label: "Development of service level agreements", group: "managedit" },
  { code: "72600000", label: "Computer support and consultancy services", group: "managedit" },
  { code: "72610000", label: "Computer support services", group: "managedit" },
  { code: "72611000", label: "Technical computer support services", group: "managedit" },
  { code: "72700000", label: "Computer network services", group: "networking" },
  { code: "72710000", label: "Local area network services", group: "networking" },
  { code: "72720000", label: "Wide area network services", group: "connectivity" },
  { code: "72800000", label: "Computer audit and testing services", group: "cyber" },
  { code: "72810000", label: "Computer audit services", group: "cyber" },
  { code: "72820000", label: "Computer testing services", group: "cyber" },
  { code: "72900000", label: "Computer back-up and catalogue conversion services", group: "cloud" },
  { code: "72910000", label: "Computer back-up services", group: "cloud" },
  // ---- Security services (79xxxxxx) ----
  { code: "79710000", label: "Security services", group: "cyber" },
  { code: "79713000", label: "Guard services", group: "cctv" },
  { code: "79417000", label: "Safety consultancy services", group: "cyber" },
  // ---- Software & hardware supply (48xxxxxx / 30xxxxxx) ----
  { code: "48000000", label: "Software package and information systems", group: "managedit" },
  { code: "48200000", label: "Networking, Internet and intranet software package", group: "networking" },
  { code: "48210000", label: "Networking software package", group: "networking" },
  { code: "48214000", label: "Network operating system software package", group: "networking" },
  { code: "48219000", label: "Miscellaneous networking software package", group: "networking" },
  { code: "48219300", label: "Administration software package", group: "networking" },
  { code: "48219500", label: "Switch or router software package", group: "networking" },
  { code: "48219800", label: "Bridge software package", group: "networking" },
  { code: "48220000", label: "Internet and intranet software package", group: "networking" },
  { code: "48222000", label: "Web server software package", group: "cloud" },
  { code: "48223000", label: "Electronic mail software package", group: "microsoft" },
  { code: "48224000", label: "Web page editing software package", group: "managedit" },
  { code: "48300000", label: "Document creation, drawing, imaging, scheduling and productivity software package", group: "microsoft" },
  { code: "48310000", label: "Document creation software package", group: "microsoft" },
  { code: "48400000", label: "Business transaction and personal business software package", group: "microsoft" },
  { code: "48440000", label: "Financial analysis and accounting software package", group: "microsoft" },
  { code: "48450000", label: "Time accounting or human resources software package", group: "microsoft" },
  { code: "48480000", label: "Sales, marketing and business intelligence software package", group: "microsoft" },
  { code: "48481000", label: "Sales or marketing software package", group: "microsoft" },
  { code: "48482000", label: "Business intelligence software package", group: "microsoft" },
  { code: "48490000", label: "Procurement software package", group: "microsoft" },
  { code: "48500000", label: "Communication and multimedia software package", group: "telecoms" },
  { code: "48510000", label: "Communication software package", group: "telecoms" },
  { code: "48515000", label: "Video-conferencing software package", group: "av" },
  { code: "48517000", label: "IT software package", group: "managedit" },
  { code: "48600000", label: "Database and operating software package", group: "managedit" },
  { code: "48700000", label: "Software package utilities", group: "managedit" },
  { code: "48730000", label: "Security software package", group: "cyber" },
  { code: "48731000", label: "File security software package", group: "cyber" },
  { code: "48732000", label: "Data security software package", group: "cyber" },
  { code: "48760000", label: "Virus protection software package", group: "cyber" },
  { code: "48761000", label: "Anti-virus software package", group: "cyber" },
  { code: "48780000", label: "System, storage and content management software package", group: "cloud" },
  { code: "48781000", label: "System management software package", group: "managedit" },
  { code: "48782000", label: "Storage management software package", group: "cloud" },
  { code: "48800000", label: "Information systems and servers", group: "cloud" },
  { code: "48810000", label: "Information systems", group: "managedit" },
  { code: "48820000", label: "Servers", group: "cloud" },
  { code: "48821000", label: "Network servers", group: "cloud" },
  { code: "48822000", label: "Computer servers", group: "cloud" },
  { code: "48823000", label: "File servers", group: "cloud" },
  { code: "48824000", label: "Printer servers", group: "managedit" },
  { code: "48825000", label: "Web servers", group: "cloud" },
  { code: "48900000", label: "Miscellaneous software package and computer systems", group: "managedit" },
  { code: "48920000", label: "Office automation software package", group: "microsoft" },
  { code: "48921000", label: "Automation system", group: "microsoft" },
  { code: "48930000", label: "Training and entertainment software package", group: "managedit" },
  { code: "48980000", label: "Programming languages and tools", group: "managedit" },
  { code: "30200000", label: "Computer equipment and supplies", group: "managedit" },
  { code: "30210000", label: "Data-processing machines (hardware)", group: "managedit" },
  { code: "30213000", label: "Personal computers", group: "managedit" },
  { code: "30213100", label: "Portable computers", group: "managedit" },
  { code: "30213300", label: "Desktop computer", group: "managedit" },
  { code: "30230000", label: "Computer-related equipment", group: "managedit" },
  { code: "30233000", label: "Media storage and reader devices", group: "cloud" },
  { code: "30237000", label: "Parts, accessories and supplies for computers", group: "managedit" },
  { code: "30237200", label: "Computer accessories", group: "managedit" },
  { code: "30237300", label: "Computer supplies", group: "managedit" },
  { code: "30231000", label: "Computer screens and consoles", group: "av" },
  { code: "30231300", label: "Display screens", group: "av" },
  { code: "30231320", label: "Touch screen monitors", group: "av" },
  // ---- Hosting / data centre ----
  { code: "72317000", label: "Data storage services", group: "cloud" },
  { code: "72322000", label: "Data management services", group: "cloud" },
  { code: "72330000", label: "Content or data standardization and classification services", group: "cloud" },
  { code: "48510000", label: "Communication software package", group: "telecoms" },
];

export function normaliseCpv(code: string | number | null | undefined): string | null {
  if (code == null) return null;
  const digits = String(code).replace(/\D/g, "");
  if (digits.length < 8) return null;
  return digits.slice(0, 8);
}
